name: "\U0001F41E Bug Report"
description: Create a report to help us improve pangora
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Found a bug? Please fill out the sections below. ðŸ‘
        Thanks for taking the time to fill out this bug report!
        For front end issues, use [pangora-ui](https://github.com/PangoraWeb/pangora-ui)
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you create a bug report please do the following.
      options:
        - label: Is this a bug report? For questions or discussions use https://programming.dev/c/pangora
          required: true
        - label: Did you check to see if this issue already exists?
          required: true
        - label: Is this only a single bug? Do not put multiple bugs in one issue.
          required: true
        - label: Is this a backend issue? Use the [pangora-ui](https://github.com/PangoraWeb/pangora-ui) repo for UI / frontend issues.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A summary of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Describe the steps to reproduce the bug.
        The better your description is _(go 'here', click 'there'...)_ the fastest you'll get an _(accurate)_ resolution.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: technical
    attributes:
      label: Technical Details
      description: |
        - Please post your log: `sudo docker-compose logs > pangora_log.out`.
        - What OS are you trying to install pangora on?
        - Any browser console errors?
    validations:
      required: true
  - type: input
    id: pangora-backend-version
    attributes:
      label: Version
      description: Which Pangora backend version do you use? Displayed in the footer.
      placeholder: ex. BE 0.17.4
    validations:
      required: true
  - type: input
    id: pangora-instance
    attributes:
      label: Pangora Instance URL
      description: Which Pangora instance do you use? (The site address)
